const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Physics,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Exps.IID,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{arkaplan: 0},
	{verticalSliderEmpty: 0},
	{verticalSliderFill: 0},
	{aktif: 0},
	{DragDrop: 0},
	{verticalSliderBtn: 0},
	{masa: 0},
	{Basınç: 0},
	{Hacim: 0},
	{mol: 0},
	{gazSabiti: 0},
	{isCelcius: 0},
	{sıcaklık: 0},
	{basincText: 0},
	{hacimText: 0},
	{molText: 0},
	{sicaklikText: 0},
	{solboru: 0},
	{sağboru: 0},
	{pistonlubuton: 0},
	{pistonsuzbuton: 0},
	{val: 0},
	{touchHold: 0},
	{anahtar: 0},
	{soğukbuton: 0},
	{sıcakbuton: 0},
	{arka: 0},
	{bostank: 0},
	{piston: 0},
	{pistonluiskelet: 0},
	{öncam: 0},
	{baseValue: 0},
	{genel: 0},
	{ekGaz: 0},
	{ates: 0},
	{buz: 0},
	{imlec: 0},
	{isDark: 0},
	{switchBtn: 0},
	{switchBox: 0},
	{ov: 0},
	{isExiting: 0},
	{Physics: 0},
	{MoveTo: 0},
	{gas: 0},
	{duvar: 0},
	{valfCikis: 0},
	{pistonHandle: 0},
	{cikar: 0},
	{ekle: 0},
	{boruHat: 0},
	{vakumCikis: 0},
	{valfGiris: 0},
	{vakumGiris: 0},
	{kacakTespit: 0},
	{interaktif: 0},
	{pVal: 0},
	{vVal: 0},
	{nVal: 0},
	{rVal: 0},
	{tVal: 0},
	{currentFrame: 0},
	{pistonluMode: 0},
	{gasAnimSpeed: 0},
	{heatValue: 0},
	{targetGasSpeed: 0},
	{minGasCount: 0},
	{gasCount: 0},
	{maxGasCount: 0},
	{opacityMin: 0},
	{opacityMax: 0},
	{gasTransferRate: 0},
	{gasTransferRateAcc: 0},
	{gasTransferMax: 0},
	{pistonTargetY: 0},
	{pistonMaxSpeed: 0},
	{addGas: 0},
	{eraseGas: 0},
	{doldurAnahtarPistonSpeed: 0},
	{bosaltAnahtarPistonSpeed: 0},
	{doldurOpacitySpeed: 0},
	{bosaltOpacitySpeed: 0},
	{dy: 0},
	{step: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	verticalSliderEmpty: class extends self.ISpriteInstance {},
	verticalSliderFill: class extends self.ISpriteInstance {},
	verticalSliderBtn: class extends self.ISpriteInstance {},
	masa: class extends self.ISpriteInstance {},
	Basınç: class extends self.ISpriteInstance {},
	Hacim: class extends self.ISpriteInstance {},
	mol: class extends self.ISpriteInstance {},
	gazSabiti: class extends self.ISpriteInstance {},
	sıcaklık: class extends self.ISpriteInstance {},
	basincText: class extends self.ITextInstance {},
	hacimText: class extends self.ITextInstance {},
	molText: class extends self.ITextInstance {},
	sicaklikText: class extends self.ITextInstance {},
	solboru: class extends self.ISpriteInstance {},
	sağboru: class extends self.ISpriteInstance {},
	pistonlubuton: class extends self.ISpriteInstance {},
	pistonsuzbuton: class extends self.ISpriteInstance {},
	anahtar: class extends self.ISpriteInstance {},
	soğukbuton: class extends self.ISpriteInstance {},
	sıcakbuton: class extends self.ISpriteInstance {},
	arka: class extends self.ISpriteInstance {},
	bostank: class extends self.ISpriteInstance {},
	piston: class extends self.ISpriteInstance {},
	pistonluiskelet: class extends self.ISpriteInstance {},
	öncam: class extends self.ISpriteInstance {},
	genel: class extends self.ISpriteInstance {},
	ekGaz: class extends self.ISpriteInstance {},
	ates: class extends self.ISpriteInstance {},
	buz: class extends self.ISpriteInstance {},
	imlec: class extends self.ISpriteInstance {},
	switchBtn: class extends self.ISpriteInstance {},
	switchBox: class extends self.ISpriteInstance {},
	gas: class extends self.ISpriteInstance {},
	duvar: class extends self.ISpriteInstance {},
	valfCikis: class extends self.ISpriteInstance {},
	pistonHandle: class extends self.ISpriteInstance {},
	cikar: class extends self.ISpriteInstance {},
	ekle: class extends self.ISpriteInstance {},
	boruHat: class extends self.ISpriteInstance {},
	vakumCikis: class extends self.ISpriteInstance {},
	valfGiris: class extends self.ISpriteInstance {},
	vakumGiris: class extends self.ISpriteInstance {},
	kacakTespit: class extends self.ISpriteInstance {},
	interaktif: class extends self.ISpriteInstance {}
}